version: "3.8"

services:
  backend:
    build:
      context: ./server           # Path to backend directory
    container_name: flask-backend
    ports:
      - "8001:8001"
    networks:
      - app-network

  frontend:
    build:
      context: ./client           # Path to frontend directory
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

